pool:
  vmImage: 'vs2017-win2016'

name: $(VersionPrefix)-$(Build.BuildId)

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/Polyrific.Project.Core/

variables:
  BuildConfiguration: 'Release'
  PackageVersion: $(Build.BuildNumber)
  VersionPrefix: 1.0.0-preview

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: src/Polyrific.Project.Core/Polyrific.Project.Core.csproj

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: src/Polyrific.Project.Core/Polyrific.Project.Core.csproj
    arguments: '--configuration $(BuildConfiguration)'

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.9.2'
  inputs:
    versionSpec: 4.9.2

- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack
    packagesToPack: src/Polyrific.Project.Core/Polyrific.Project.Core.nuspec
    versioningScheme: byEnvVar
    versionEnvVar: PackageVersion

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
